server:
  port: ${APP_PORT:18080}

spring:
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/hmdp?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowLoadLocalInfile=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:1234}

  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:123321}
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

logging:
  level:
    # 打印 SQL
    org.hibernate.SQL: debug
    # 打印绑定参数（? 的值）
    org.hibernate.type.descriptor.sql.BasicBinder: trace