spring:
  application:
    name: hmdp

  # 默认激活开发环境
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true      # 目标库已有表时也能落地到 V1
    clean-disabled: true           # 禁用 Flyway 清库
    placeholders:
      dataDir: ops/flyway/data   # 让 ${dataDir} 在 SQL 里可用

mybatis-plus:
  type-aliases-package: com.hmdp.entity

logging:
  level:
    com.hmdp: debug


