name: Deploy to AWS EC2

on:
  push:
    branches:
      - main   # 每次 main 分支更新时触发部署

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build jar
        run: |
          ./mvnw clean package -DskipTests

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository }}:latest
            docker rm -f hmdp-app || true
            docker run -d --name hmdp-app --restart unless-stopped \
              -p 18080:18080 -p 18082:18082 \
              -e SERVER_PORT=18080 \
              -e SPRING_DATASOURCE_URL="jdbc:mysql://hmdp-db.cnquoqea8loi.eu-central-1.rds.amazonaws.com:3306/hmdp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC" \
              -e SPRING_DATASOURCE_USERNAME="root" \
              -e SPRING_DATASOURCE_PASSWORD='${{ secrets.RDS_PASSWORD }}' \
              -e SPRING_REDIS_HOST="redis" -e SPRING_REDIS_PORT="6379" \
              -e SPRING_FLYWAY_ENABLED="true" \
              ghcr.io/${{ github.repository }}:latest
            docker system prune -f
